### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by SansPseudoFix** [scaleway/image-app-openvpn#13]
Hi,
when i'm trying to send an email with icedove through my vpn, it doesn't work (time out). But I can receive emails... When I shut down my vpn connection, it works fine.
Tried with my own domain (gandi) and with openmailbox.org.

I've take a look to logs, but saw nothing useful. Is there an iptables issue?

**Comment by moul** [comment]
Did you open the SMTP port: https://www.scaleway.com/docs/deploy-wordpress-in-seconds/#-Step-2--Open-the-mail-ports-to-send-email ?

**Comment by SansPseudoFix** [comment]
Ugh! No... Sorry. It works like a charm now :)

Thx!

**Comment by moul** [comment]
You're welcome :)

**Comment by reiz** [comment]
@moul why are you blocking SMTP by default? It took me 2 hours to figure this out :-(
